### ISSUE TITLE
crear,corregir o completar metodo "CambiarEstadoPedidoPendienteAprobacion(idPedido, aprobado)

### ISSUE THREAD

**Issue by jonysnm** [jonysnm/AD2017#16]
este metodo se va a utilizar para que el gerente de la sucursal apruebe o rechace un pedido.
el metodo recibe el idPedido y el nuevo EStado.

* El metodo actualiza el campo Estado (lo pone en AprobadoenSucursal o RechazadoenSucursal) . Para identificar que el pedido ya fue aprobado y esta listo para procesar en el deposito.

* Crear el metodo en todas las capas involucradas (desde la pantalla hasta el DTO)

--> ya esta bastante avanzado: ver que falta para cerrar el issue

**Comment by mauriciocabj** [comment]
Lo termina de subir @fiantorno.

Saludos
