### ISSUE TITLE
Crear enum "EstadoAprobacionPedidoCliente"

### ISSUE THREAD

**Issue by jonysnm** [jonysnm/AD2017#18]
*crear un enum que contenga los textos "Aprobado" y "Rechazado"
la idea es usarlo para cambiar el estado del pedido cuando lo revisa el gerente de la sucursal y dice si el pedido se puede procesar o se rechaza directamente en la sucursal

**Comment by arturogs** [comment]
Listo
cambie en todos lados donde tocaba el estado que era string y saque un estado que estaba en el server que no se usaba
